---
- name: Debian 12 provisioning
  hosts: all
  gather_facts: true

  vars_files:
    - ../vars/user_setup.yml
    - ../vars/common_pkgs.yml
    - ../vars/virtualbox_guest.yml

  roles:
    - pluggero.upgrade
    - pluggero.virtualbox_guest
    - pluggero.common_pkgs
    - pluggero.user_setup
