---
roles:
  - src: pluggero.virtualbox_guest
    version: 2.4.0
  - src: pluggero.user_setup
    version: 2.5.0
  - src: pluggero.common_pkgs
    version: 2.3.0
  - src: pluggero.upgrade
    version: 1.0.0
